from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT as WD_ALIGN_VERTICAL
from docx.enum.section import WD_ORIENTATION


default_text_checklist = {
    "font_name": "Times New Roman",
    "font_size": 13.0,
    "font_bald": False,
    "font_italic": False,
    "font_underline": False,
    "font_color": False,
    "font_back_color": False,
    "alignment": 3,
    "keep_with_next": False,
    "page_break_before": False,
    "space_before": 0.0,
    "space_after": 0.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 1.25,
    "line_spacing": 1.5,
}
default_heading1_checklist = {
    "font_name": "Times New Roman",
    "font_size": 16.0,
    "font_bald": True,
    "font_italic": False,
    "font_underline": False,
    "font_color": False,
    "font_back_color": False,
    "alignment": 1,
    "keep_with_next": True,
    "page_break_before": True,
    "space_before": 0.0,
    "space_after": 12.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 0.0,
    "line_spacing": 1.5,
    "is_list": True
}
default_heading2_checklist = {
    "font_name": "Times New Roman",
    "font_size": 14.0,
    "font_bald": True,
    "font_italic": False,
    "font_underline": False,
    "font_color": False,
    "font_back_color": False,
    "alignment": 1,
    "keep_with_next": True,
    "page_break_before": False,
    "space_before": 12.0,
    "space_after": 6.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 0.0,
    "line_spacing": 1.5,
    "is_list": True
}
default_heading3_checklist = {
    "font_name": "Times New Roman",
    "font_size": 13.0,
    "font_bald": True,
    "font_italic": False,
    "font_underline": False,
    "font_color": False,
    "font_back_color": False,
    "alignment": 1,
    "keep_with_next": True,
    "page_break_before": False,
    "space_before": 8.0,
    "space_after": 4.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 0.0,
    "line_spacing": 1.5,
    "is_list": True
}
default_list_checklist = {
    "left_indent_base": 1.25,
    "left_indent_mod": 0.75,
    "first_line_indent": -0.75,
}
default_table_headings_checklist = {
    "font_name": "Times New Roman",
    "font_size": 11.0,
    "font_bald": True,
    "font_italic": False,
    "font_underline": False,
    "font_color": False,
    "font_back_color": False,
    "alignment": 1,
    "vert_alignment": 1,
    "keep_with_next": False,
    "page_break_before": False,
    "space_before": 0.0,
    "space_after": 0.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 0.0,
    "line_spacing": 1.0,
}
default_table_text_checklist = {
    "font_name": "Times New Roman",
    "font_size": 11.0,
    "font_bald": False,
    "font_italic": False,
    "font_underline": False,
    "font_color": False,
    "font_back_color": False,
    "alignment": 0,
    "vert_alignment": 1,
    "keep_with_next": False,
    "page_break_before": False,
    "space_before": 0.0,
    "space_after": 0.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 0.0,
    "line_spacing": 1.0,
}
default_table_name_checklist = {
    "format_regex": "Таблица <N> - <Название>.",
    "font_name": "Times New Roman",
    "font_size": 13.0,
    "font_color": False,
    "font_back_color": False,
    "alignment": 0,
    "keep_with_next": True,
    "page_break_before": False,
    "space_before": 13.0,
    "space_after": 0.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 0.0,
    "line_spacing": 1.0,
}
default_text_after_table_checklist = {
    "font_name": "Times New Roman",
    "font_size": 13.0,
    "font_bald": False,
    "font_italic": False,
    "font_underline": False,
    "font_color": False,
    "font_back_color": False,
    "alignment": 3,
    "keep_with_next": False,
    "page_break_before": False,
    "space_before": 13.0,
    "space_after": 0.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 1.25,
    "line_spacing": 1.5,
}
default_image_checklist = {
    "alignment": 1,
    "keep_with_next": True,
    "space_before": 6.0,
    "space_after": 0.0,
    "first_line_indent": 0,
    "line_spacing": 1,
}
default_image_name_checklist = {
    "format_regex": "Рисунок <N> - <Название>.",
    "font_name": "Times New Roman",
    "font_size": 11.0,
    "font_bald": True,
    "font_italic": True,
    "font_color": False,
    "font_back_color": False,
    "alignment": 1,
    "keep_with_next": False,
    "page_break_before": False,
    "space_before": 0.0,
    "space_after": 6.0,
    "left_indent": 0,
    "right_indent": 0,
    "first_line_indent": 0,
    "line_spacing": 1,
}
default_margins_checklist = {
    "top_margin": 2.0,
    "bottom_margin": 2.0,
    "left_margin": 3.0,
    "right_margin": 1.5,
    "orientation": 0
}

default_enable_elem_check = {
    "table_headings_top": True,
    "table_headings_left": False,
    "table_title": True,
    "paragraph_after_table": True,
    "enable_pic_title": True
}
